import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import employeeRoutes from "./routes/employeesRoutes.js";
import departmentRoutes from "./routes/departmentsRoutes.js";
import designationRoutes from "./routes/designationsRoutes.js";
import emergencyContactRoutes from "./routes/employeeEmergencyContactsRoutes.js";
import documentRoutes from "./routes/employeeDocumentsRoutes.js";
import bankDetailRoutes from "./routes/employeeBankDetailsRoutes.js";
import shiftAssignmentRoutes from "./routes/employeeShiftAssignmentsRoutes.js";
import salaryStructureRoutes from "./routes/employeeSalaryStructuresRoutes.js";
import overtimeRateRoutes from "./routes/employeeOvertimeRatesRoutes.js";
import companySettingsRoutes from "./routes/companySettingsRoutes.js";
import userRoutes from "./routes/usersRoutes.js";
import roleRoutes from "./routes/rolesRoutes.js";
import permissionRoutes from "./routes/permissionsRoutes.js";
import userRoleRoutes from "./routes/userRolesRoutes.js";
import rolePermissionRoutes from "./routes/rolePermissionsRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import shiftRoutes from "./routes/shiftsRoutes.js";
import holidayRoutes from "./routes/holidaysRoutes.js";
import attendanceRuleRoutes from "./routes/attendanceRulesRoutes.js";
import attendanceRoutes from "./routes/attendanceRoutes.js";
import attendanceCorrectionRoutes from "./routes/attendanceCorrectionsRoutes.js";
import workLocationRoutes from "./routes/workLocationsRoutes.js";
import overtimeRoutes from "./routes/overtimeRoutes.js";
import leaveTypeRoutes from "./routes/leaveTypesRoutes.js";
import leaveRequestRoutes from "./routes/leaveRequestsRoutes.js";
import salaryComponentRoutes from "./routes/salaryComponentsRoutes.js";
import statutoryConfigRoutes from "./routes/statutoryConfigsRoutes.js";
import salaryStructureMasterRoutes from "./routes/salaryStructuresRoutes.js";
import bonusIncentiveRoutes from "./routes/bonusIncentivesRoutes.js";
import payrollPeriodRoutes from "./routes/payrollPeriodsRoutes.js";
import payrollRoutes from "./routes/payrollRoutes.js";
import payslipRoutes from "./routes/payslipsRoutes.js";
import expenseCategoryRoutes from "./routes/expenseCategoriesRoutes.js";
import expenseClaimRoutes from "./routes/expenseClaimsRoutes.js";
import dailyReportRoutes from "./routes/dailyReportsRoutes.js";
import performanceRoutes from "./routes/performanceRoutes.js";
import notificationRoutes from "./routes/notificationsRoutes.js";
import auditLogRoutes from "./routes/auditLogsRoutes.js";
import inventoryUnitRoutes from "./routes/inventoryUnitsRoutes.js";
import inventoryCategoryRoutes from "./routes/inventoryCategoriesRoutes.js";
import stockLocationRoutes from "./routes/stockLocationsRoutes.js";
import supplierRoutes from "./routes/suppliersRoutes.js";
import rawMaterialRoutes from "./routes/rawMaterialsRoutes.js";
import rawMaterialStockRoutes from "./routes/rawMaterialStockRoutes.js";
import purchaseRequestRoutes from "./routes/purchaseRequestsRoutes.js";
import purchaseOrderRoutes from "./routes/purchaseOrdersRoutes.js";
import goodsReceiptRoutes from "./routes/goodsReceiptsRoutes.js";
import qualityInspectionRoutes from "./routes/qualityInspectionsRoutes.js";
import finishedProductRoutes from "./routes/finishedProductsRoutes.js";
import billOfMaterialRoutes from "./routes/billsOfMaterialsRoutes.js";
import productionOrderRoutes from "./routes/productionOrdersRoutes.js";
import finishedProductStockRoutes from "./routes/finishedProductStockRoutes.js";
import customerRoutes from "./routes/customersRoutes.js";
import salesOrderRoutes from "./routes/salesOrdersRoutes.js";
import dispatchRoutes from "./routes/dispatchesRoutes.js";
import invoiceRoutes from "./routes/invoicesRoutes.js";
import customerReturnRoutes from "./routes/customerReturnsRoutes.js";
import machineRoutes from "./routes/machinesRoutes.js";
import toolRoutes from "./routes/toolsRoutes.js";
import toolAssignmentRoutes from "./routes/toolAssignmentsRoutes.js";
import stockTransferRoutes from "./routes/stockTransfersRoutes.js";
import stockAdjustmentRoutes from "./routes/stockAdjustmentsRoutes.js";
import damageLossRoutes from "./routes/inventoryDamageLossRoutes.js";
import inventoryNotificationRuleRoutes from "./routes/inventoryNotificationRulesRoutes.js";

dotenv.config();

connectDB();

const app = express();
app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.send("API is running...");
});

app.get("/api/health", (req, res) => {
    //check Db connection and report status
    if (connectDB) {
        res.status(200).json({ status: "OK", message: "Database connection is healthy" });
    }else{
        res.status(500).json({ status: "ERROR", message: "Database connection is not healthy" });
    }
});

app.use("/api/employees", employeeRoutes);
app.use("/api/departments", departmentRoutes);
app.use("/api/designations", designationRoutes);
app.use("/api/emergency-contacts", emergencyContactRoutes);
app.use("/api/documents", documentRoutes);
app.use("/api/bank-details", bankDetailRoutes);
app.use("/api/shift-assignments", shiftAssignmentRoutes);
app.use("/api/salary-structures", salaryStructureRoutes);
app.use("/api/overtime-rates", overtimeRateRoutes);
app.use("/api/company-settings", companySettingsRoutes);
app.use("/api/users", userRoutes);
app.use("/api/roles", roleRoutes);
app.use("/api/permissions", permissionRoutes);
app.use("/api/user-roles", userRoleRoutes);
app.use("/api/role-permissions", rolePermissionRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/shifts", shiftRoutes);
app.use("/api/holidays", holidayRoutes);
app.use("/api/attendance-rules", attendanceRuleRoutes);
app.use("/api/attendance", attendanceRoutes);
app.use("/api/attendance-corrections", attendanceCorrectionRoutes);
app.use("/api/work-locations", workLocationRoutes);
app.use("/api/overtime", overtimeRoutes);
app.use("/api/leave-types", leaveTypeRoutes);
app.use("/api/leave-requests", leaveRequestRoutes);
app.use("/api/salary-components", salaryComponentRoutes);
app.use("/api/statutory-configs", statutoryConfigRoutes);
app.use("/api/salary-structures-master", salaryStructureMasterRoutes);
app.use("/api/bonus-incentives", bonusIncentiveRoutes);
app.use("/api/payroll-periods", payrollPeriodRoutes);
app.use("/api/payroll", payrollRoutes);
app.use("/api/payslips", payslipRoutes);
app.use("/api/expense-categories", expenseCategoryRoutes);
app.use("/api/expense-claims", expenseClaimRoutes);
app.use("/api/daily-reports", dailyReportRoutes);
app.use("/api/performance", performanceRoutes);
app.use("/api/notifications", notificationRoutes);
app.use("/api/audit-logs", auditLogRoutes);
app.use("/api/inventory-units", inventoryUnitRoutes);
app.use("/api/inventory-categories", inventoryCategoryRoutes);
app.use("/api/stock-locations", stockLocationRoutes);
app.use("/api/suppliers", supplierRoutes);
app.use("/api/raw-materials", rawMaterialRoutes);
app.use("/api/raw-material-stock", rawMaterialStockRoutes);
app.use("/api/purchase-requests", purchaseRequestRoutes);
app.use("/api/purchase-orders", purchaseOrderRoutes);
app.use("/api/goods-receipts", goodsReceiptRoutes);
app.use("/api/quality-inspections", qualityInspectionRoutes);
app.use("/api/finished-products", finishedProductRoutes);
app.use("/api/bills-of-materials", billOfMaterialRoutes);
app.use("/api/production-orders", productionOrderRoutes);
app.use("/api/finished-product-stock", finishedProductStockRoutes);
app.use("/api/customers", customerRoutes);
app.use("/api/sales-orders", salesOrderRoutes);
app.use("/api/dispatches", dispatchRoutes);
app.use("/api/invoices", invoiceRoutes);
app.use("/api/customer-returns", customerReturnRoutes);
app.use("/api/machines", machineRoutes);
app.use("/api/tools", toolRoutes);
app.use("/api/tool-assignments", toolAssignmentRoutes);
app.use("/api/stock-transfers", stockTransferRoutes);
app.use("/api/stock-adjustments", stockAdjustmentRoutes);
app.use("/api/damage-loss-reports", damageLossRoutes);
app.use("/api/inventory-notification-rules", inventoryNotificationRuleRoutes);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
